name: gym-dev

services:
  gym-config-server:
    container_name: gym-config-server
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8888:8888"
    networks:
      - gym-dev-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev,native
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  gym-dev-network:
    external: true
