server:
  port: 8082

spring:
  mongodb:
    uri: mongodb://admin:password@gym-workload-database:27017/gym_workload_database?authSource=admin&directConnection=true
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
    consumer:
      group-id: gym-workload-consumer-group

application:
  security:
    internal-prefix: "/internal"
    public-prefix: "/api"
    endpoints:
      public-endpoints:
        - "/api/v1/workload"
        - "/actuator/**"
        - "/swagger-ui/**"
        - "/swagger-ui.html"
        - "/v3/api-docs/**"
  auth:
    url: "http://gym-auth-service:8083"
    path: "/internal/v1/token"
  swagger:
    server-url: "http://localhost:8082"
    server-description: "Dev server"
  jwt:
    auth-header: "Authorization"
    bearer-prefix: "Bearer"
  clients:
    auth: "gym-auth-service"
  messaging:
    topics:
      trainer-workload: trainer.workload.events

management:
  endpoint:
    health:
      show-components: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,custom,env
  metrics:
    tags:
      application: gym-workload-service
  prometheus:
    metrics:
      export:
        enabled: true
  info:
    env:
      enabled: true

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: WARN
